### ISSUE TITLE
Proper way to extract blobs?

### ISSUE THREAD

**Issue by Geofferey** [jacks84/device_oneplus_hotdogb#1]
When attempting extract blobs from hotdogb running OOS 10.0.12 using extract-files.sh in this device tree I noticed it replaces files in vendor/onelus/sm8150-common. Is this the way it's supposed to work? I also noticed many of the files can not be found when extracting using the script like some are specific to the oneplus 7 pro. Another approach I tried, after git resetting vendor  sm8150-common repo was to mount OOS 10.0.12 vendor.img and copy the files into vendor/oneplus/hotdogb/proprietary/vendor/*. I got the build to finish but major issues with everything from cellular to audio. I'm sure this is because vendor/oneplus/hotdogb blobs are not the correct ones or similar, but I'm not sure how to fix so vendor/oneplus/hotdogb, device/oneplus/hotdog etc. will be the way it was on your last build. I have built other ROMs from sources in past but I need a little bit of direction for these sources.

**Comment by jacks84** [comment]
The android 10 blobs are all solid. There is no need to extract anything for Android 10. But yes, when you run the extract_files script vs a oos dump it pulls the files that are listed in the proprietary files.txt in the hotdogb tree, and dumps them to vendor.

See this for more reference:

https://wiki.lineageos.org/extracting_blobs_from_zips.html

Just use the dumped ota from git.rip, clone it to a directory in home/android/system_dump/ then from the hotdogb directory run ./extract-files.sh ~/android/system_dump/ the script runs and so long as you don't edit anything from proprietary files.txt, it will pull and update any files for vendor. Hope that helps

**Comment by jacks84** [comment]
https://git.rip/dumps/oneplus/oneplus7t

**Comment by Geofferey** [comment]
@jacks84 

> The android 10 blobs are all solid. There is no need to extract anything for Android 10...

I should not have to run extract-files.sh at all from the hotdogb device tree then? As it stands vendor/oneplus/hotdogb/proprietary/* is un-populated after setup-makefiles.sh and only populated after hotdogb/extract-files.sh. I'm afraid device/oneplus/hotdogb/extract-files.sh is borking sm8150-common even tho it gets me to complete a build because it overwrites files... For whatever reason I can't seem to get this to build working and my last one powered off immediately at setup screen. Maybe I'm trying to populate vendor/oneplus/hotdogb/* with blobs from the wrong dump (10 QKQ1.190716.003 2010191120). Which op7t dump did you extract from? 

If at all possible would you be willing to PM me on telegram? My handle is the same as here @geofferey. I don't want to be rude asking for so much, however,  if I could get just a little bit of your time over next build or two I can surely get it to work without this painful trial and error process at 3hr a build. Once the blob situation or whatever is figured out I shouldn't really need anymore help and I do not want to be a menace either. Honestly, you're only person to build this with your sources beside one other person and he couldn't really tell me much of anything. I did try to join the RR group you were at one time but I was too late and you moved on.
